// Generated by tools/gen_lut.py from tools/ntsc.py - do not edit.
// 18.42 mV per DAC code into a 75 ohm load.
localparam [5:0] LVL_SYNC = 6'd0;
localparam [5:0] LVL_BLANK = 6'd16;
localparam [5:0] LVL_BURST_HI = 6'd24;
localparam [5:0] LVL_BURST_LO = 6'd8;
