#!/usr/bin/env python3
"""Writes common/ntsc_lut.hex and common/ntsc_levels.vh from ntsc.py.

Run again after changing anything in ntsc.py (levels, saturation, DAC).
"""
import os
import ntsc

here = os.path.dirname(os.path.abspath(__file__))
common = os.path.join(here, "..", "common")

table = ntsc.lut()
assert len(table) == 1024 and all(0 <= c <= ntsc.CODE_MAX for c in table)
with open(os.path.join(common, "ntsc_lut.hex"), "w") as f:
    for code in table:
        f.write("%02x\n" % code)

with open(os.path.join(common, "ntsc_levels.vh"), "w") as f:
    f.write("// Generated by tools/gen_lut.py from tools/ntsc.py - do not edit.\n")
    f.write("// %.2f mV per DAC code into a 75 ohm load.\n" % (ntsc.V_PER_CODE * 1000))
    for name in ("SYNC", "BLANK", "BURST_HI", "BURST_LO"):
        f.write("localparam [5:0] LVL_%s = 6'd%d;\n" % (name, getattr(ntsc, name)))

print("levels: sync %d  blank %d  black %.1f  white %.1f  burst %d..%d  (%.1f mV/code)" % (
    ntsc.SYNC, ntsc.BLANK, ntsc.ire_to_code(ntsc.BLACK_IRE), ntsc.ire_to_code(ntsc.WHITE_IRE),
    ntsc.BURST_LO, ntsc.BURST_HI, ntsc.V_PER_CODE * 1000))
print("white -> %s   yellow -> %s   blue -> %s" % (
    ntsc.colour_codes(0xFF), ntsc.colour_codes(0xFC), ntsc.colour_codes(0x03)))
assert ntsc.crc16(b"123456789") == 0x29B1
